/*
 * gen-data.js
 * ----------------------------------------------------------------------------
 * Reads the five source-of-truth CSV files in the project root and emits
 * js/data.js, a self-contained module of parsed game data. This keeps the
 * CSVs authoritative while letting the browser tool run offline (file://),
 * where fetching local CSVs is blocked by the browser.
 *
 * Re-run after editing any CSV:   node tools/gen-data.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data');
const OUT = path.join(ROOT, 'js', 'data.js');

const FILES = {
  outcomes: 'spinner-outcomes.csv',
  values: 'spinner-values.csv',
  fastMoney: 'fast-money-targets.csv',
  build: 'build-costs.csv',
  repair: 'repair-costs.csv',
};

function read(name) {
  return fs.readFileSync(path.join(DATA_DIR, name), 'utf8');
}

// Minimal CSV parser: splits on lines and commas. The source CSVs contain no
// quoted fields, so a naive split is correct and keeps this dependency-free.
function parseCSV(text) {
  return text
    .replace(/\r\n/g, '\n')
    .split('\n')
    .filter((line) => line.length > 0)
    .map((line) => line.split(','));
}

const num = (s) => {
  const n = Number(String(s).trim());
  return Number.isFinite(n) ? n : null;
};

// --- Spinner Outcomes: index, category, outcome --------------------------
function parseOutcomes() {
  return parseCSV(read(FILES.outcomes)).map((r) => ({
    index: num(r[0]),
    category: r[1].trim(),
    outcome: r[2].trim(),
  }));
}

// --- Spinner values: outcome family -> human description -----------------
function parseValues() {
  const out = {};
  for (const r of parseCSV(read(FILES.values))) {
    const key = r[0].trim();
    if (!key) continue;
    out[key] = r.slice(1).join(',').trim();
  }
  return out;
}

// --- Fast Money trigger points: queue -> survey-point target -------------
function parseFastMoney() {
  const rows = parseCSV(read(FILES.fastMoney));
  return rows
    .slice(1) // drop header
    .map((r) => ({ queue: num(r[0]), target: num(r[1]) }))
    .filter((r) => r.queue != null);
}

// --- Builder cost tables: costs[level][building] = [base, 2star, 3star] --
// Level appears only on the first building row of each block; forward-fill it.
function parseCostTable(name) {
  const rows = parseCSV(read(name)).slice(1); // drop header
  const table = {}; // level -> { building -> [base,2,3] }
  let level = null;
  for (const r of rows) {
    const lvlCell = r[0].trim();
    if (lvlCell) {
      const m = lvlCell.match(/(\d+)/);
      if (m) level = Number(m[1]);
    }
    const bldCell = r[1].trim();
    const bm = bldCell.match(/(\d+)/);
    if (level == null || !bm) continue;
    const building = Number(bm[1]);
    if (!table[level]) table[level] = {};
    table[level][building] = [num(r[2]), num(r[3]), num(r[4])];
  }
  return table;
}

const data = {
  generatedAt: new Date().toISOString(),
  source: FILES,
  outcomes: parseOutcomes(),
  values: parseValues(),
  fastMoney: parseFastMoney(),
  buildCosts: parseCostTable(FILES.build),
  repairCosts: parseCostTable(FILES.repair),
};

// Quick integrity report to stderr so regressions are obvious on regen.
const levels = Object.keys(data.buildCosts).length;
console.error(`outcomes:   ${data.outcomes.length} (expect 72)`);
console.error(`fastMoney:  ${data.fastMoney.length} triggers`);
console.error(`buildCosts: ${levels} levels`);
console.error(`repairCosts:${Object.keys(data.repairCosts).length} levels`);

const banner =
  '// AUTO-GENERATED by tools/gen-data.js from the source CSVs. Do not edit by hand.\n' +
  `// Generated: ${data.generatedAt}\n`;

const body =
  banner +
  'window.GAME_DATA = ' +
  JSON.stringify(data, null, 2) +
  ';\n';

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, body);
console.error(`\nWrote ${OUT} (${(body.length / 1024).toFixed(1)} KB)`);
